### ISSUE TITLE
error with newest sklearn version?

### ISSUE THREAD

**Issue by ManuelAllh** [hmmlearn/hmmlearn#103]
Hi,

I get the following error when I import _BaseHMM to define my own HMM:

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> import hmmlearn
>>> import numpy
>>> import scipy
>>> sklearn.__version__
'0.17.1'
>>> hmmlearn.__version__
'0.2.0'
>>> numpy.__version__
'1.10.4'
>>> scipy.__version__
'0.17.0'
>>> from hmmlearn.hmm import _BaseHMM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hmmlearn/hmm.py", line 14, in <module>
    from sklearn import cluster
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/__init__.py", line 14, in <module>
    from .bicluster import SpectralBiclustering, SpectralCoclustering
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/bicluster/__init__.py", line 1, in <module>
    from .spectral import SpectralCoclustering, SpectralBiclustering
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cluster/bicluster/spectral.py", line 27, in <module>
    from sklearn.utils.validation import check_arrays
ImportError: cannot import name check_arrays
```

Do you have any ideas? Can I help with anything?

Best regards,
Manuel

**Comment by ManuelAllh** [comment]
Sorry my fault, something strange with older versions happened... now it is running

**Comment by superbobry** [comment]
No worries :)
