### ISSUE TITLE
stock analysis example gives urllib2.HTTPError: 404 for yahoo API call

### ISSUE THREAD

**Issue by BerioFlow** [hmmlearn/hmmlearn#207]
I keep getting the following error when trying to run the plot_hmm_stock_analysis.py example:

`Traceback (most recent call last):
  File "plot_hmm_stock_analysis.py", line 33, in <module>
    "INTC", datetime.date(1995, 1, 1), datetime.date(2012, 1, 6))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/finance.py", line 236, in quotes_historical_yahoo
    fh = fetch_historical_yahoo(ticker, date1, date2, cachename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/finance.py", line 197, in fetch_historical_yahoo
    with contextlib.closing(urlopen(url)) as urlfh:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found`

The error happens for the following code:
`quotes = quotes_historical_yahoo_ochl("INTC", datetime.date(1995, 1, 1), datetime.date(2012, 1, 6))
`
Which uses the matplotlib.finance module (I've already tried replacing it with the newer mpl_finance module but this is giving the same results). If anyone has a solution to this, or could pass the variable value that should be loaded into quotes that would be great too, as this is currently blocking me learning how the model in the example should work

**Comment by superbobry** [comment]
Yep, the data is no longer available. We can backport scikit-learn/scikit-learn#9010.

**Comment by HaonanTong** [comment]
Hi, I am not an expert in financial or market. I read the backport, but what is the solution to make the model works?

**Comment by Kornel** [comment]
@superbobry I've created a PR here: https://github.com/hmmlearn/hmmlearn/pull/242

**Comment by tuhinsharma** [comment]
any progress on this?

**Comment by anntzer** [comment]
Closed by https://github.com/hmmlearn/hmmlearn/pull/303.
