### ISSUE TITLE
Prediction of Multivariate Multinomial HMM

### ISSUE THREAD

**Issue by minlupe** [hmmlearn/hmmlearn#216]
I followed the tutorial and trained Multinomial HMM with training data shape (num_samples, num_feat = 4). For testing, I used the predict function on test_data (num_samples, num_feat=4). 
The predict/decode function throws an error, because dimension mismatch. It looks like the decoding output is (num_samples*num_feat, ), which is different from what I expected (num_samples).
When I switched to GaussianHMM, it works okay.
Can anyone have suggestion how to work on multivariate multinomial hmms?

**Comment by superbobry** [comment]
Could you provide the stacktrace?

**Comment by corcra** [comment]
I also have this problem, I _think_ I'm misunderstanding how the model expects inputs to be formatted for the multinomial HMM (so it may be a documentation issue rather than code).

Example code:
```
from hmmlearn import hmm
import numpy as np

# 5 different multinomial variables
n_features = 5    
 # each multinomial takes values between 0 and 4, but in theory this could vary per variable
max_val = 4
n_samples = 10
# toy data
X = np.int32(np.random.uniform(low=0, high=max_val, size=(n_samples, n_features))

model = hmm.MultinomialHMM(n_components=2)
model.fit(X)

model.decode(X)
```
... which throws this error:
```
Traceback (most recent call last):
  File "...\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-b1e5c60ea50d>", line 1, in <module>
    model.decode(X)
  File "...\Anaconda3\lib\site-packages\hmmlearn\base.py", line 313, in decode
    state_sequence[i:j] = state_sequenceij
ValueError: could not broadcast input array from shape (50) into shape (10)
```

**Comment by corcra** [comment]
Looking at the code, I suspect multivariate multinomial models just aren't supported.

**Comment by pawod** [comment]
just ran into the same issue using quite large one-hot vectors as input... is there any solution yet?

**Comment by fastluca** [comment]
Hello, I've the same problem here.. any suggestion?

**Comment by shayneobrien** [comment]
any idea how to modify source code to support multivariate multinomial prediction?
