### ISSUE TITLE
another issuse

### ISSUE THREAD

**Issue by albumns** [hmmlearn/hmmlearn#27]
Hello

I am trying to use msmb, but it failed with messages

Traceback (most recent call last):
  File "/usr/bin/msmb", line 9, in <module>
    load_entry_point('msmbuilder==3.3.0.dev0', 'console_scripts', 'msmb')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/scripts/msmb.py", line 5, in <module>
    from ..commands import *
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/commands/__init__.py", line 5, in <module>
    from .fit import GaussianFusionHMMCommand
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/commands/fit.py", line 16, in <module>
    from ..hmm import GaussianFusionHMM
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/hmm/__init__.py", line 3, in <module>
    from .vmhmm import VonMisesHMM
  File "/usr/lib64/python2.7/site-packages/msmbuilder-3.3.0.dev0-py2.7-linux-x86_64.egg/msmbuilder/hmm/vmhmm.py", line 17, in <module>
    from sklearn.hmm import _BaseHMM
ImportError: No module named hmm

I found this solution:

https://github.com/hmmlearn/hmmlearn/issues/7

but it doesn't work for me. Since I cannot find :

+    config.add_subpackage("utils")
     return config

in setup.py file....

Could anybody give me some advices?

thx a lot

**Comment by superbobry** [comment]
I seems that the current version of [msmbuilder](https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/hmm/vmhmm.py#L17) doesn't support the latest `sklearn` which doesn't have `hmm` package. 

You can try installing an older version of `sklearn` (0.15.1) manually and then  running `msb`.
