### ISSUE TITLE
'import warnings' missing in hmm.py

### ISSUE THREAD

**Issue by davereikher** [hmmlearn/hmmlearn#273]
When training a HMM with GMMHMM, I get the following error:
Traceback (most recent call last):
  File "hmmtry.py", line 24, in <module>
    model = hmm.GMMHMM(n_components = 5, n_mix=2, covariance_type="full", n_iter = 100)
  File "/home/dave/virtualenvs/py3env/lib/python3.5/site-packages/hmmlearn/hmm.py", line 548, in __init__
    warnings.warn("Fitting a GMMHMM with {0!r} covariance type "
NameError: name 'warnings' is not defined

Adding 'import warnings' in hmm.py fixes this

**Comment by anntzer** [comment]
Fixed as of master by #107.
