### ISSUE TITLE
Error for 'covariance_type'  in GaussianHMM model 

### ISSUE THREAD

**Issue by Borreguin** [hmmlearn/hmmlearn#274]
X is a vector of samples, and I got a trained model from it. I make a copy of this model because I want to do some operations with this copy (like modify the order of the means, or the startprob, etc).  I create a new model from scratch and setup the model as you see in the code below. The problem is when I try to do a prediction of my X vector:

```python
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)
from hmmlearn.hmm import GaussianHMM
import numpy as np

#samples:
X = np.array([[-1.03573482, -1.03573482],
       [ 6.62721065, 11.62721065],
       [ 3.19196949,  8.19196949],
       [ 0.38798214,  0.38798214],
       [ 2.56845104,  7.56845104],
       [ 5.03699793, 10.03699793],
       [ 5.87873937, 10.87873937],
       [ 4.27000819, -1.72999181],
       [ 4.02692237, -1.97307763],
       [ 5.7222677 , 10.7222677 ]])``


# Trainning a new model over samples:
model = GaussianHMM(n_components=3, covariance_type="diag").fit(X)

# Create a new copy of the trained model: 
new_model = GaussianHMM(n_components=3, covariance_type="diag")
new_model.startprob_ = model.startprob_
new_model.transmat_ = model.transmat_ 
new_model.means_ = model.means_
new_model.covars_ = model.covars_

# Predict from X:
X_N, Z_N = new_model.predict(X) 
```
The predict function gives me the following error:
``` python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "\Python\Python36\site-packages\hmmlearn\base.py", line 334, in predict
    _, state_sequence = self.decode(X, lengths)
  File "\Python36\site-packages\hmmlearn\base.py", line 294, in decode
    self._check()
  File "\Python36\site-packages\hmmlearn\hmm.py", line 175, in _check
    self.n_components)
  File "\lib\site-packages\sklearn\mixture\gmm.py", line 763, in _validate_covars
    raise ValueError("'diag' covars must have shape "
ValueError: 'diag' covars must have shape (n_components, n_dim)
```

It seems like there is a problem in the 'covars' array due to the covariance_type. But since both model has 'covariance_type' = 'diag'. I don't realize why this error exists? Could you help me to fix this error.

**Comment by brenlla1** [comment]
When inputing `covars_` in hmmlearn, they are of lesser dimensionality than the output  `covars_` after fitting. In hmmlearn 0.2.1 the following patch works fine:

```
new_model.covars_ = np.array([np.diag(i) for i in model.covars_])
# take only diagonal values and remove one dimension
new_model.predict(X)
# array([0, 2, 1, 0, 1, 2, 2, 1, 0, 2])

new_model.covars_:
array([[[ 4.54890133,  0.        ],
        [ 0.        ,  0.94518975]],

       [[ 0.49725906,  0.        ],
        [ 0.        , 20.59491647]],

       [[ 0.32191652,  0.        ],
        [ 0.        ,  0.32191652]]])

Output covars now have an extra dimension
```
