### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by xxinl** [hmmlearn/hmmlearn#28]
Hi, got this error when trying to import... (win7 x64 python3.4). any ideas? Thanks.

>>> from hmmlearn import hmm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\hmmlearn-0.1.1-py3.4-win-amd64.egg\hmmlearn\hmm.py", line 22, in <module>
    from .base import _BaseHMM, decoder_algorithms
  File "C:\Anaconda3\lib\site-packages\hmmlearn-0.1.1-py3.4-win-amd64.egg\hmmlearn\base.py", line 12, in <module>
    from . import _hmmc
  File "stringsource", line 269, in init hmmlearn._hmmc (hmmlearn/_hmmc.c:17699)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 1: invalid start byte

**Comment by xxinl** [comment]
fixed by building using cygwin compiler
python setup.py build --compiler=cygwin
