### ISSUE TITLE
ValueError: component 0 of 'full' covars must be symmetric, positive-definite

### ISSUE THREAD

**Issue by VertexC** [hmmlearn/hmmlearn#285]
Hi, I have looked into the previous issue on that but none of them solves my problem. 
I am using GuassianHMM but It doesn't seem to train the model properly.
```python
Traceback (most recent call last):
  File "src/playground/HMM_hmmlearn.py", line 49, in <module>
    prob, state_seq = model.decode(x_m.T)
  File "/Users/bowenchen/State_Space_Model_on_Gene/ssm-env/lib/python3.6/site-packages/hmmlearn/base.py", line 294, in decode
    self._check()
  File "/Users/bowenchen/State_Space_Model_on_Gene/ssm-env/lib/python3.6/site-packages/hmmlearn/hmm.py", line 165, in _check
    super(GaussianHMM, self)._check()
  File "/Users/bowenchen/State_Space_Model_on_Gene/ssm-env/lib/python3.6/site-packages/hmmlearn/base.py", line 524, in _check
    .format(self.transmat_.sum(axis=1)))
ValueError: rows of transmat_ must sum to 1.0 (got [1. 0. 1. 1.])

def initialize():
    g = 0
    while g < G:
        x_m[:, g] = abs(
            np.matrix(np.random.multivariate_normal((theta_m.T * y_m[:, g]).flatten().tolist()[0], np.eye(E)))).T
        g += 1

if __name__ == '__main__':
    initialize()
    model = hmm.GaussianHMM(n_components=K, covariance_type="full",n_iter=30)
    iterate_times = 5
    final_score = -math.inf
    scores = []
    print(x_m)
    while iterate_times > 0:
        model.fit(x_m.T)
        print(model.covars_)
        prob, state_seq = model.decode(x_m.T)
        scores.append(model.score(x_m.T))
        iterate_times -= 1
    print(scores)
```
And there is the print out variable
```
x_m
[[1.68185378e-01 1.02232212e+00 2.68666556e-01 8.49854862e-01
  4.19318133e-01]
 [1.04003708e-01 8.84099494e-01 1.64639541e+00 1.61692603e+00
  1.79678081e+00]
 [5.78889521e-01 6.46720353e-01 1.51399590e+00 1.87850812e-03
  3.36270387e+00]]

covars_
[[[ 0.01243624 -0.02659715  0.03280353]
  [-0.02659715  0.13925868 -0.1131393 ]
  [ 0.03280353 -0.1131393   0.10895525]]

 [[ 0.01        0.01        0.01      ]
  [ 0.01        0.01        0.01      ]
  [ 0.01        0.01        0.01      ]]

 [[ 0.01        0.01        0.01      ]
  [ 0.01        0.01        0.01      ]
  [ 0.01        0.01        0.01      ]]

 [[ 0.01        0.01        0.01      ]
  [ 0.01        0.01        0.01      ]
  [ 0.01        0.01        0.01      ]]]
```

Anyone have some ideas?
Thanks.

**Comment by clizarralde** [comment]
Same issue here ...

**Comment by maheshdosm** [comment]
Same issue with me

**Comment by jyyang5** [comment]
Same here

**Comment by outlace** [comment]
Same here

**Comment by wanlonghub** [comment]
> Same here, however, if I change `covariance_type="diag"` instead of "full" then it works

yeah,  it works, but why?

**Comment by bvegetas** [comment]
The training process involves Cholesky decomposition of covariance matrices which requires that all eigenvalues of covariance matrices should be non-negative. Numerical errors, however small it might seem, will accumulate in the computation process and make those eigenvalues "negative" in the calculated result even though they should be close to zero but non-negative in reality.

**Comment by anntzer** [comment]
You are trying to fit very short sequences (in the OP's case, 5 points x 3 coordinates per point, so a total of 15 scalar values) to very large models (4 states; each state is represented by 3 means (1 per coordinate) and 6 (1+2+3) independent covariance matrix entries; so a total of 27 scalar parameters).  Hence the fit is degenerate; I will add a clearer error in that case.
