### ISSUE TITLE
Error while running locally the repo

### ISSUE THREAD

**Issue by fmorenopino** [hmmlearn/hmmlearn#334]
Hello,

I´m trying to run my own version of the repository (locally, to be able to apply some changes) but I´m constantly facing one error while running the file "plot_hmm_sampling.py", which reports: "ImportError: cannot import name _hmmc". I installed the "setup.py" file (as said here: https://github.com/hmmlearn/hmmlearn/issues/3 and here: https://github.com/hmmlearn/hmmlearn/issues/53) but it keeps reporting the same error anyway.

Is it a known error? How could I run locally my own version of the code to perform some changes on it?

Regards,
Fernando.

**Comment by chieni** [comment]
In case you're still having this error, I was able to run a local version of the package by first using the command `python setup.py build_ext --inplace` on the "setup.py" file.

**Comment by lowkeygit** [comment]
I also have similar problem.
I got "ImportError: cannot import name '_hmmc'" when I'm trying to "from hmmlearn import hmm".

**Comment by anntzer** [comment]
Run `pip install .` from the local source checkout.

**Comment by brenlla1** [comment]
Same problem here.

When I run `pip install .` I get error `"python setup.py egg_info" failed with error code 1 in....`

When I try `python setup.py build_ext --inplace` I get error in line 11, `ModuleNotFoundError: No module named 'setuptools'` (I do have setuptools installed though)

**Comment by anntzer** [comment]
What does `python -c "import setuptools"` do?
What is the full error message with `pip install .`?

**Comment by brenlla1** [comment]
the full error message from `pip install .` is rather long:

```
(base) C:\Users\hmmlearn-master>pip install .
Processing c:\users\hmmlearn-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\a\AppData\Local\Temp\pip-req-build-6fwzm1h2\setup.py",
line 97, in <module>
        "gui_scripts": [],
      File "C:\Users\a\Anaconda3\lib\site-packages\setuptools\__init__.py",
line 145, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\a\Anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\Users\a\Anaconda3\lib\site-packages\setuptools\dist.py", line
 447, in __init__
        k: v for k, v in attrs.items()
      File "C:\Users\a\Anaconda3\lib\distutils\dist.py", line 292, in __init
__
        self.finalize_options()
      File "C:\Users\a\Anaconda3\lib\site-packages\setuptools\dist.py", line
 739, in finalize_options
        ep.load()(self, ep.name, value)
      File "c:\users\a\appdata\local\temp\pip-req-build-6fwzm1h2\.eggs\setup
tools_scm-3.3.3-py3.7.egg\setuptools_scm\integration.py", line 17, in version_ke
yword
        dist.metadata.version = get_version(**value)
      File "c:\users\a\appdata\local\temp\pip-req-build-6fwzm1h2\.eggs\setup
tools_scm-3.3.3-py3.7.egg\setuptools_scm\__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "c:\users\a\appdata\local\temp\pip-req-build-6fwzm1h2\.eggs\setup
tools_scm-3.3.3-py3.7.egg\setuptools_scm\__init__.py", line 113, in _do_parse
        "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_ro
ot
    LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\a\\AppData\\Local\\Temp\\pip-req-build-6fwzm1h2'.

    Make sure you're either building from a fully intact git repository or PyPI
tarballs. Most other sources (such as GitHub's tarballs, a git checkout without
the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/ar
chive/master.zip use git+https://github.com/user/proj.git#egg=proj

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\a\Ap
pData\Local\Temp\pip-req-build-6fwzm1h2\
```

**Comment by anntzer** [comment]
Can you try off a fresh clone? just pushed a possible fix.

**Comment by brenlla1** [comment]
Thanks! Just tried new clone, now I get different error:

```
(base) C:\Users\a>cd C:\Users\a\Documents\hmmlearn-master-2\hmmlearn-mas
ter

(base) C:\Users\a\Documents\hmmlearn-master-2\hmmlearn-master>pip install .
Processing c:\users\a\documents\hmmlearn-master-2\hmmlearn-master
Requirement already satisfied: numpy>=1.10 in c:\users\a\anaconda3\lib\site-
packages (from hmmlearn==0+unknown) (1.16.2)
Requirement already satisfied: scikit-learn>=0.16 in c:\users\a\anaconda3\li
b\site-packages (from hmmlearn==0+unknown) (0.20.3)
Requirement already satisfied: scipy>=0.13.3 in c:\users\a\anaconda3\lib\sit
e-packages (from scikit-learn>=0.16->hmmlearn==0+unknown) (1.2.1)
Building wheels for collected packages: hmmlearn
  Building wheel for hmmlearn (setup.py) ... error
  Complete output from command C:\Users\a\Anaconda3\python.exe -u -c "import
 setuptools, tokenize;__file__='C:\\Users\\a\\AppData\\Local\\Temp\\pip-req-
build-l3_ryylw\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.rea
d().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist
_wheel -d C:\Users\a\AppData\Local\Temp\pip-wheel-052cpc65 --python-tag cp37
:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\hmmlearn
  copying lib\hmmlearn\base.py -> build\lib.win-amd64-3.7\hmmlearn
  copying lib\hmmlearn\hmm.py -> build\lib.win-amd64-3.7\hmmlearn
  copying lib\hmmlearn\stats.py -> build\lib.win-amd64-3.7\hmmlearn
  copying lib\hmmlearn\utils.py -> build\lib.win-amd64-3.7\hmmlearn
  copying lib\hmmlearn\_utils.py -> build\lib.win-amd64-3.7\hmmlearn
  copying lib\hmmlearn\_version.py -> build\lib.win-amd64-3.7\hmmlearn
  copying lib\hmmlearn\__init__.py -> build\lib.win-amd64-3.7\hmmlearn
  creating build\lib.win-amd64-3.7\hmmlearn\tests
  copying lib\hmmlearn\tests\conftest.py -> build\lib.win-amd64-3.7\hmmlearn\tes
ts
  copying lib\hmmlearn\tests\test_base.py -> build\lib.win-amd64-3.7\hmmlearn\te
sts
  copying lib\hmmlearn\tests\test_gaussian_hmm.py -> build\lib.win-amd64-3.7\hmm
learn\tests
  copying lib\hmmlearn\tests\test_gmm_hmm.py -> build\lib.win-amd64-3.7\hmmlearn
\tests
  copying lib\hmmlearn\tests\test_gmm_hmm_new.py -> build\lib.win-amd64-3.7\hmml
earn\tests
  copying lib\hmmlearn\tests\test_multinomial_hmm.py -> build\lib.win-amd64-3.7\
hmmlearn\tests
  copying lib\hmmlearn\tests\test_utils.py -> build\lib.win-amd64-3.7\hmmlearn\t
ests
  copying lib\hmmlearn\tests\__init__.py -> build\lib.win-amd64-3.7\hmmlearn\tes
ts
  running build_ext
  _hmmc.c
  c:\users\a\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot ope
n include file: 'io.h': No such file or directory
  error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools
\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBU
G /MD -IC:\Users\a\Anaconda3\lib\site-packages\numpy\core\include -IC:\Users
\a\Anaconda3\include -IC:\Users\a\Anaconda3\include -IC:\Program Files (
x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include /
Tclib\hmmlearn\_hmmc.c /Fobuild\temp.win-amd64-3.7\Release\lib\hmmlearn\_hmmc.ob
j" failed with exit status 2

  ----------------------------------------
  Failed building wheel for hmmlearn
  Running setup.py clean for hmmlearn
Failed to build hmmlearn
Installing collected packages: hmmlearn
  Found existing installation: hmmlearn 0.2.1
    Uninstalling hmmlearn-0.2.1:
      Successfully uninstalled hmmlearn-0.2.1
  Running setup.py install for hmmlearn ... error
    Complete output from command C:\Users\a\Anaconda3\python.exe -u -c "impo
rt setuptools, tokenize;__file__='C:\\Users\\a\\AppData\\Local\\Temp\\pip-re
q-build-l3_ryylw\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.r
ead().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" ins
tall --record C:\Users\a\AppData\Local\Temp\pip-record-330f024n\install-reco
rd.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\hmmlearn
    copying lib\hmmlearn\base.py -> build\lib.win-amd64-3.7\hmmlearn
    copying lib\hmmlearn\hmm.py -> build\lib.win-amd64-3.7\hmmlearn
    copying lib\hmmlearn\stats.py -> build\lib.win-amd64-3.7\hmmlearn
    copying lib\hmmlearn\utils.py -> build\lib.win-amd64-3.7\hmmlearn
    copying lib\hmmlearn\_utils.py -> build\lib.win-amd64-3.7\hmmlearn
    copying lib\hmmlearn\_version.py -> build\lib.win-amd64-3.7\hmmlearn
    copying lib\hmmlearn\__init__.py -> build\lib.win-amd64-3.7\hmmlearn
    creating build\lib.win-amd64-3.7\hmmlearn\tests
    copying lib\hmmlearn\tests\conftest.py -> build\lib.win-amd64-3.7\hmmlearn\t
ests
    copying lib\hmmlearn\tests\test_base.py -> build\lib.win-amd64-3.7\hmmlearn\
tests
    copying lib\hmmlearn\tests\test_gaussian_hmm.py -> build\lib.win-amd64-3.7\h
mmlearn\tests
    copying lib\hmmlearn\tests\test_gmm_hmm.py -> build\lib.win-amd64-3.7\hmmlea
rn\tests
    copying lib\hmmlearn\tests\test_gmm_hmm_new.py -> build\lib.win-amd64-3.7\hm
mlearn\tests
    copying lib\hmmlearn\tests\test_multinomial_hmm.py -> build\lib.win-amd64-3.
7\hmmlearn\tests
    copying lib\hmmlearn\tests\test_utils.py -> build\lib.win-amd64-3.7\hmmlearn
\tests
    copying lib\hmmlearn\tests\__init__.py -> build\lib.win-amd64-3.7\hmmlearn\t
ests
    running build_ext
    _hmmc.c
    c:\users\a\anaconda3\include\pyconfig.h(59): fatal error C1083: Cannot o
pen include file: 'io.h': No such file or directory
    error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildToo
ls\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDE
BUG /MD -IC:\Users\a\Anaconda3\lib\site-packages\numpy\core\include -IC:\Use
rs\a\Anaconda3\include -IC:\Users\a\Anaconda3\include -IC:\Program Files
 (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include
 /Tclib\hmmlearn\_hmmc.c /Fobuild\temp.win-amd64-3.7\Release\lib\hmmlearn\_hmmc.
obj" failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of hmmlearn
  Moving to c:\users\a\anaconda3\lib\site-packages\hmmlearn
   from c:\users\a\anaconda3\lib\site-packages\~mmlearn
  Moving to c:\users\a\anaconda3\lib\site-packages\hmmlearn-0.2.1-py3.7.egg-
info
   from c:\users\a\anaconda3\lib\site-packages\~mmlearn-0.2.1-py3.7.egg-info

Command "C:\Users\a\Anaconda3\python.exe -u -c "import setuptools, tokenize;
__file__='C:\\Users\\a\\AppData\\Local\\Temp\\pip-req-build-l3_ryylw\\setup.
py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\
n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\a
bl21\AppData\Local\Temp\pip-record-330f024n\install-record.txt --single-version-
externally-managed --compile" failed with error code 1 in C:\Users\a\AppData
\Local\Temp\pip-req-build-l3_ryylw\

(base) C:\Users\a\Documents\hmmlearn-master-2\hmmlearn-master>

```

**Comment by anntzer** [comment]
that looks like a problem with your setup, see e.g. https://stackoverflow.com/questions/40018405/cython-cannot-open-include-file-io-h-no-such-file-or-directory https://github.com/Jonathan-LeRoux/lws/issues/4 and similar google results.

**Comment by brenlla1** [comment]
All right, thanks again. I'll look into that.
Installation works when I do `conda install -c omnia hmmlearn`. Could you briefly explain why it works that way but not on my local repo?

**Comment by anntzer** [comment]
Because conda provides a precompiled package.
