### ISSUE TITLE
min_covar not implemented @ hmm.GMMHMM

### ISSUE THREAD

**Issue by RonTeichner** [hmmlearn/hmmlearn#365]
I had very very small covariance values so the log-probabilities were too-high causing the exponent of log-probabilities to be inf. I fixed the issue by changing at the end of the m-step:
self.covars_ = new_cov + self.min_covar. Previously it was self.covars_ = new_cov

**Comment by anntzer** [comment]
I made some improvements to the handling of degenerate cases in https://github.com/hmmlearn/hmmlearn/commit/db2d06991c37812b38330b32588c12c55fe021fd; can you check whether master works better for you?

**Comment by RonTeichner** [comment]
Sure, I'll let you know, later today
________________________________

**Comment by RonTeichner** [comment]
Hey, I tried with the master version and I get the same error:

/home/ront/.local/lib/python3.7/site-packages/hmmlearn/hmm.py:962: RuntimeWarning: invalid value encountered in true_divide
  new_cov = new_cov_numer / new_cov_denom
Some rows of transmat_ have zero sum because no transition from the state was ever observed

My fix which is self.covars_ = new_cov + self.min_covar at the end of the m-step fixed the issue.

Thank you for your time and for sharing your code

**Comment by anntzer** [comment]
Please provide an example to repro the issue.

**Comment by RonTeichner** [comment]
[errorExample.tar.gz](https://github.com/hmmlearn/hmmlearn/files/3892311/errorExample.tar.gz)
Attached is a notebook and a small dataset. Run the notebook and you will see the errors. 

(The notebook is originally from https://github.com/kastnerkyle/kastnerkyle.github.io. 
I made many changes, previously it trained using a self-defined hmmgmm class, I wanted to switch to your package)

**Comment by RonTeichner** [comment]
If you have trouble running it due to missing libraries I'll provide a simpler example. If you prefer I can also provide a python file instead of the notebook

**Comment by anntzer** [comment]
Please extract just the relevant dataset and single hmmlearn call that showcases the issue.

**Comment by RonTeichner** [comment]
[example.tar.gz](https://github.com/hmmlearn/hmmlearn/files/3893272/example.tar.gz)
Here it is, a very simple py file

**Comment by anntzer** [comment]
Thanks.
My feeling is that min_covars is just papering over a real numerical error somewhere else; in theory even a zero covariance should be handled fine.  I'll see whether I can fix that...

**Comment by RonTeichner** [comment]
I think I disagree. When you calculate the log-probability it is not a probability you substitute the observed value in but a density function. If the variance is very small the peak of the density function has a huge value. That is because the integral of the density function must sum to 1. It becomes a delta function.

**Comment by anntzer** [comment]
Then it should be possible to repro the issue as well (using synthetic data) with GaussianHMM too?  To be honest, while I understand the GaussianHMM part quite well (I think) I'm not so comfortable with the GMMHMM code.

**Comment by RonTeichner** [comment]
sklearn used to have hmmgmm and hmmGaussian modules. I thought that in this repository I found it. Is it so?
and I'm sure that with noise-free data you can have this problem in GaussianHMM as well

**Comment by anntzer** [comment]
sklearn didn't want to maintain this module and its original author isn't using it anymore, that's how I inherited it.
I'm not absolutely opposed to the change you propose, but I just want to understand it better first.

**Comment by RonTeichner** [comment]
Who is the original author?
B.T.W, I'm new to the open-source code world. I found an issue with a code I use for free so I wanted to contribute my part. 
Why do you support this code? What is your motivation? seriously... 
I never constructed an open-source library

**Comment by anntzer** [comment]
Authors are listed in https://github.com/hmmlearn/hmmlearn/blob/master/AUTHORS.rst.
I appreciate your contribution so will consider it, but as you mention there's no pay for it so that's why I can't put in the fix (i.e., in this case, think about whether min_covars is the right thing to use) *now*.
I'm maintaining the library because 1) it's useful to me, 2) quite often feedback from users is also beneficial for my own use cases, 3) I know it well enough that I can hack on it as needed much better than I would be able to do on a closed-source library... all I can think of right now ;)

**Comment by RonTeichner** [comment]
Good reasons. Ok, I'm about to use it a bit, I'll update you if something else pops up. Nice talking to you, good night (at least for me)

**Comment by anntzer** [comment]
I spent a bit more time looking at it.  It looks like this happens because you are using n_mix = 1.  But then, why not just use GaussianHMM, which is (AFAICT) equivalent and simpler in that case?

**Comment by RonTeichner** [comment]
I always try to first check an algorithm with the simple scenario.
You see that switching to GaussianHMM solves the problem?
________________________________

**Comment by anntzer** [comment]
Yes.  The underflow occurs because you have a single mix with zero probability which can thus not be normalized.

**Comment by RonTeichner** [comment]
So your solution will be to internally call GaussianHMM when n_mix ==1?
Or to change the normalization alg?
________________________________

**Comment by anntzer** [comment]
I pushed a change to handle that.

**Comment by RonTeichner** [comment]
I'll make a pull tomorrow and let you know
________________________________

**Comment by RonTeichner** [comment]
Hey, I ran the small example I sent you and I get the error:

Traceback (most recent call last):
  File "/media/ront/Files/Projects/kastnerkyle.github.io/posts/single-speaker-word-recognition-with-hidden-markov-models/exampleScript.py", line 9, in <module>
    GMMHMM(n_components=6, n_mix=1, n_iter=100, covariance_type='diag', min_covar=1e-3).fit(modelInput[0], modelInput[1]).score(modelInput[2])
  File "/home/ront/.local/lib/python3.7/site-packages/hmmlearn/base.py", line 283, in score
    self._check()
  File "/home/ront/.local/lib/python3.7/site-packages/hmmlearn/hmm.py", line 794, in _check
    .format(self.covariance_type))
ValueError: 'diag' mixture covars must be non-negative

**Comment by anntzer** [comment]
should be fixed now.

**Comment by RonTeichner** [comment]
It is fixed, it does not underflow now. But is the min_covar implemented? The motivation, as written in the documentation is "min_covar (float, optional) – Floor on the diagonal of the covariance matrix to **prevent overfitting.**". Indeed if I add the min_covar value to self.covars_ as I did before I get improved test accuracy.

**Comment by anntzer** [comment]
The fit converges to a degenerate state (with a null covariance eigenvalue).  This is essentially saying that your model is not actually a good one to describe your data.  Sure, you can artificially constrain the fit to "pretend" the problem doesn't exist, but that's just a hack...

**Comment by RonTeichner** [comment]
I'll think it through, thanks
________________________________
