### ISSUE TITLE
fitting multivariate binary time series via MultinomialHMM

### ISSUE THREAD

**Issue by stefan-de** [hmmlearn/hmmlearn#371]
Hi,
I'm trying to uncover hidden states of a multivariate binary time series.
Data:
X.shape = (6282, 144) -> 144 features containing only binary data.
[liste.zip](https://github.com/hmmlearn/hmmlearn/files/3975669/liste.zip)

X.shape
startproba = np.array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
transitions = np.array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                        [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]])

model = MultinomialHMM(n_components = 10, startprob_prior = startproba, \
                       transmat_prior= transitions)

model.fit(X)
model.predict(X)
Traceback (most recent call last):

  File "<ipython-input-13-1d5eefb37c1b>", line 18, in <module>
    model.predict(X)

  File "C:\Users\TASD\Anaconda3\lib\site-packages\hmmlearn\base.py", line 375, in predict
    _, state_sequence = self.decode(X, lengths)

  File "C:\Users\TASD\Anaconda3\lib\site-packages\hmmlearn\base.py", line 354, in decode
    state_sequence[i:j] = state_sequenceij

ValueError: could not broadcast input array from shape (892044) into shape (6282)

Any suggestions?

**Comment by anntzer** [comment]
Please provide a fully reproducible example that I can simply copy-paste.

**Comment by stefan-de** [comment]
[mre_miltinom_hmm_learn.zip](https://github.com/hmmlearn/hmmlearn/files/3992325/mre_miltinom_hmm_learn.zip)

**Comment by anntzer** [comment]
I can't repro locally, I get ValueError: startprob_ must sum to 1.0 (got nan)
I would guess that your data is incorrectly encoded in any case, it looks like one-hot whereas MultinomialHMM wants just the category numbers.
