### ISSUE TITLE
 ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by Ayush-Porwal** [hmmlearn/hmmlearn#372]
Hi, I am using windows 10. I recently installed anaconda3 with 3.7 version of python. While importing sklearn I am getting the following error. Please help asap.

The error is as follows.

(mining) C:\Users\prom_>python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\sklearn\__init__.py", line 82, in <module>
    from .base import clone
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\sklearn\base.py", line 20, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\sklearn\utils\__init__.py", line 27, in <module>
    from .fixes import np_version
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\sklearn\utils\fixes.py", line 18, in <module>
    import scipy.stats
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\stats\__init__.py", line 379, in <module>
    from .stats import *
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\stats\stats.py", line 182, in <module>
    from . import distributions
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 24, in <module>
    from scipy import optimize
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\optimize\__init__.py", line 391, in <module>
    from ._minimize import *
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
    from .eigen import *
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "C:\Users\prom_\.conda\envs\mining\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by AlexVestin** [comment]
@Ayush-Porwal Did you activate the environment?

**Comment by anntzer** [comment]
This is not the sklearn issue tracker, but the hmmlearn one.  Please keep the discussion on topic here.
PS: "Please help asap" is unlikely to make maintainers willing to help you, no one is paid to do this.
