### ISSUE TITLE
Fitting with n_samples*n_features larger than unique state number

### ISSUE THREAD

**Issue by aakiselyov** [hmmlearn/hmmlearn#416]
I'm trying to fit GaussianHMM on a dataset with n_samples=30, n_features=30, containing 100 unique values. Below is a sample code:

```
import random
import numpy as np
import hmmlearn.hmm

UNIQUE_LABELS = 100
N_SAMPLES = 30
N_FEATURES = 30

train = np.array(random.choices(range(UNIQUE_LABELS), k=N_SAMPLES*N_FEATURES), dtype=int)
train = train.reshape(N_SAMPLES, N_FEATURES)

hmm = hmmlearn.hmm.GaussianHMM(n_components=UNIQUE_LABELS, random_state=0)
hmm.fit(train)
```

which gives the following error:

```
Fitting a model with 15999 free scalar parameters with only 900 data points will result in a degenerate solution.
Traceback (most recent call last):
  File "foo.py", line 13, in <module>
    hmm.fit(train)
  File "/..../venv/lib/python3.8/site-packages/hmmlearn/base.py", line 462, in fit
    self._init(X, lengths=lengths)
  File "/..../venv/lib/python3.8/site-packages/hmmlearn/hmm.py", line 208, in _init
    kmeans.fit(X)
  File "/..../venv/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 984, in fit
    self._check_params(X)
  File "/..../venv/lib/python3.8/site-packages/sklearn/cluster/_kmeans.py", line 812, in _check_params
    raise ValueError(f"n_samples={X.shape[0]} should be >= "
ValueError: n_samples=30 should be >= n_clusters=100.
```

Is it a bug? I understood that `n_components` means states corresponding to each feature, which are used to e.g. construct feature vectors when calling `hmm.sample`.

**Comment by anntzer** [comment]
AFAIK, fitting a fully connected HMM with 100 states (I make no judgment as to whether this is the correct model in your case) is basically "never" going to work with the standard approaches implemented in hmmlearn.
