### ISSUE TITLE
Error running stock example

### ISSUE THREAD

**Issue by Lila14** [hmmlearn/hmmlearn#49]
I downloaded and ran the stock example, without any modifications, and received an error.

```
python plot_hmm_stock_analysis.py 
/usr/lib/python2.7/site-packages/pkg_resources.py:1054: UserWarning: /home/lila/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)

==========================
Gaussian HMM of stock data
==========================

This script shows how to use Gaussian HMM.
It uses stock price data, which can be obtained from yahoo finance.
For more information on how to get stock prices with matplotlib, please refer
to date_demo1.py of matplotlib.


fitting to HMM and decoding ...Traceback (most recent call last):
  File "plot_hmm_stock_analysis.py", line 57, in <module>
    model.fit([X])
  File "build/bdist.linux-x86_64/egg/hmmlearn/base.py", line 400, in fit
  File "/usr/lib64/python2.7/site-packages/sklearn/utils/validation.py", line 373, in check_array
    array.ndim)
ValueError: Found array with dim 3. Expected <= 2

```

**Comment by Lila14** [comment]
Sorry, I realized that I was using the wrong version of the script.
