### ISSUE TITLE
index out of bounds in emissionprob_

### ISSUE THREAD

**Issue by bapowellphys** [hmmlearn/hmmlearn#538]
Upon training my hmm, during validation I sometimes get an index out of bounds error from emissionprob_, 
e.g. last two lines of the trace:

    return self.emissionprob_[:, X.squeeze(1)].T
IndexError: index 370 is out of bounds for axis 1 with size 339

This occurs when I run score on a test sequence.

I've tracked this down to a situation where there are observable states with higher numerical representations in the validation set than in the training set.  It appears that the indices in the emission probability matrix correspond directly to the numerical values of the observables; if a larger numeral is seen during validation or testing, an index out of bounds seems inevitable.  This seems like an unnecessary situation, since observables that exist only in the validation set but with *smaller* numerical values simply lead to    -inf likelihoods (because they have zero probabilities in the emission matrix) rather than throwing errors.  

Can someone confirm my suspicion?

Thanks for any insight.

**Comment by alexrockhill** [comment]
Can you make an example of this with some simulated data or example data that we can use to reproduce the error please?

**Comment by bapowellphys** [comment]
Sure. 

from hmmlearn import hmm
import numpy as np

train = [[[1],[2],[3],[2]],[[2],[4],[5],[2]],[[2],[3],[3],[2]],[[1],[2],[3],[2]]]
val = [[[2],[6],[4],[2]],[[1],[2],[3],[2]]]
train_cat = np.concatenate(train)
train_lengths = np.array([len(i) for i in train])

model = hmm.CategoricalHMM(n_components=2,n_iter=20,verbose=False)  
model.fit(train_cat,train_lengths)
for i in val:
  score = model.score(i)

**Comment by Koen1999** [comment]
I got a similar problem while running unit tests. The problem is not reproducible for me, but here is the stack trace.

```
Traceback (most recent call last):
  File "C:\Users\user\project\package\file.py", line 127, in <listcomp>
    non_variational_categorical_hmm.score(sequence.reshape(-1, 1))
  File "C:\Users\user\AppData\Local\Programs\Python\venv\Lib\site-packages\hmmlearn\_emissions.py", line 27, in <lambda>
    return functools.wraps(func)(lambda *args, **kwargs: func(*args, **kwargs))
                                                         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\venv\Lib\site-packages\hmmlearn\base.py", line 226, in score
    return self._score(X, lengths, compute_posteriors=False)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\venv\Lib\site-packages\hmmlearn\base.py", line 244, in _score
    return impl(
           ^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\venv\Lib\site-packages\hmmlearn\base.py", line 256, in _score_log
    log_frameprob = self._compute_log_likelihood(sub_X)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\venv\Lib\site-packages\hmmlearn\base.py", line 606, in _compute_log_likelihood
    likelihood = self._compute_likelihood(X)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\venv\Lib\site-packages\hmmlearn\_emissions.py", line 84, in _compute_likelihood
    return self.emissionprob_[:, X.squeeze(1)].T
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: index 22 is out of bounds for axis 1 with size 21
```

**Comment by blckmaxima** [comment]
Thank you for the report.  I don't have immediate time to look into this.
However, when I do, I'll keep it in mind.

Matthew
