### ISSUE TITLE
benchmark does not run

### ISSUE THREAD

**Issue by anntzer** [hmmlearn/hmmlearn#59]
Today's git checkout.
```
$ PYTHONPATH=. python bench/speed.py
benchmarking Gaussian HMM on a sample of size 65536
generating sample... Traceback (most recent call last):
  File "bench/speed.py", line 36, in <module>
    bench_gaussian_hmm(2**16)
  File "bench/speed.py", line 26, in bench_gaussian_hmm
    sample, _states = ghmm.sample(size)
  File "/home/antony/src/hmmlearn/hmmlearn/base.py", line 366, in sample
    check_is_fitted(self, "startprob_")
  File "/home/antony/.local/lib/python3.5/site-packages/sklearn/utils/validation.py", line 678, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.utils.validation.NotFittedError: This GaussianHMM instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.
```

**Comment by superbobry** [comment]
Thanks. The benchmark isn't any good anyway, so I think I'll just remove it.
