### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by julian-ramos** [hmmlearn/hmmlearn#64]
Hi,

I tried to run the plot_hmm example but here is what I get

```python
Traceback (most recent call last):
  File "/Users/ingenia/git/hmmlearn/examples/plot_hmm_sampling.py", line 19, in <module>
    from hmmlearn import hmm
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hmmlearn/hmm.py", line 21, in <module>
    from .base import _BaseHMM, decoder_algorithms
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hmmlearn/base.py", line 8, in <module>
    from . import _hmmc
  File "__init__.pxd", line 155, in init hmmlearn._hmmc (hmmlearn/_hmmc.c:18874)
ValueError: numpy.dtype has the wrong size, try recompiling
```

I followed the instructions to install but no luck, any idea on how to solve this problem?

**Comment by superbobry** [comment]
Hello, 

I think this might happen if the version of NumPy in `PYTHONPATH` differs from the one used during compilation of `hmmlearn`. 

You can try using a virtual environment, e.g. [`virtualenv`](https://virtualenv.readthedocs.org/en/latest/) or the one provided by [`conda`](http://conda.pydata.org/docs/using/envs.html), to isolate the issue.

**Comment by julian-ramos** [comment]
Hi,

Yes you are right, after a lot of experimentation I found that eclipse was messing up with my PYTHONPATH so I was able to run the examples correctly outside of eclipse.  Learning virtualenv as we speak.

Thanks,
